In [17]:
import plotly
from plotly.graph_objs import *
import json
import pandas
from pandas.io.json import json_normalize
'''
load data from json file and flatten
'''
datafile="/Users/annejones/chiweb/data/gfs/json/tas-2m-gfs-1.0.json"
print("loading data from" + datafile)
#raw=pandas.read_json(datafile)
#df=json_normalize(raw)
#print(raw['data'].size)
with open(datafile) as f:
    d = json.load(f)
d = json_normalize(d)
df = pandas.DataFrame({'T':df['data'].loc[0]})

loading data from/Users/annejones/chiweb/data/gfs/json/tas-2m-gfs-1.0.json

In [18]:
df

               T
0      242.94154
1      242.94154
2      242.94154
3      242.94154
4      242.94154
5      242.94154
6      242.94154
7      242.94154
8      242.94154
9      242.94154
10     242.94154
11     242.94154
12     242.94154
13     242.94154
14     242.94154
15     242.94154
16     242.94154
17     242.94154
18     242.94154
19     242.94154
20     242.94154
21     242.94154
22     242.94154
23     242.94154
24     242.94154
25     242.94154
26     242.94154
27     242.94154
28     242.94154
29     242.94154
...          ...
65130  240.58154
65131  240.58154
65132  240.58154
65133  240.58154
65134  240.58154
65135  240.58154
65136  240.58154
65137  240.58154
65138  240.58154
65139  240.58154
65140  240.58154
65141  240.58154
65142  240.58154
65143  240.58154
65144  240.58154
65145  240.58154
65146  240.58154
65147  240.58154
65148  240.58154
65149  240.58154
65150  240.58154
65151  240.58154
65152  240.58154
65153  240.58154
65154  240.58154
65155  240.58154
65156  240.58154
65157  240.58154
65158  240.58154
65159  240.58154

[65160 rows x 1 columns]